### PR TITLE
Don't vaste space

### PR DESCRIPTION
**Pull request by zen0bit**
Removed a lot of empty lines from script and also printf
Removed trailing whitespaces
Consistent indentation

And removed \n where was more then one (from whole script)

Just if you like it...

### CODE REVIEW

**Comment by TuxVinyards** [comment]
The work that you did on _**OS Home pages was good and is the right way forward for collaboration**_ .

Taking an axe to my code and requesting that I turn it into something totally unusable is not.

Your request that Wimpy makes his code over-compressed was declined.  (https://github.com/quickemu-project/quickemu/pull/862)   Whether my agreement with his decision prompted you to pick up an axe is only something that you know.

I attach a screenshot  from testing on a standard 1920x1080 monitor showing everything to be fine.

Yes, if you look hard enough, you will always find a few places that any extra line space or two has crept in.  These usually get filtered out with time.  None of them are causing problems.

Screenshot at 2023-12-27 13-10-19

Any serious coder will be using a large 4K screen of course and a modern multipanel IDE with filter extensions and mini-map navigation ...   Maybe this is the move you need to make?

Screenshot at 2023-12-27 13-31-55

All the best for 2024 and for success with qrun.

**Comment by zen0bit** [comment]
Looks like I am not a serious coder. 😇Just amatuer trying to 🔪 (help). Often from mobile termux so...

Maybe it bit explain my obsession with space wasting...
 With best wishes zenobit

**Comment by lj3954** [comment]
> The work that you did on _**OS Home pages was good and is the right way forward for collaboration**_ .
> 
> Taking an axe to my code and requesting that I turn it into something totally unusable is not.
> 
> Your request that Wimpy makes his code over-compressed was declined. ([quickemu-project/quickemu#862](https://github.com/quickemu-project/quickemu/pull/862)) Whether my agreement with his decision prompted you to pick up an axe is only something that you know.
> 
> I attach a screenshot from testing on a standard 1920x1080 monitor showing everything to be fine.
> 
> Yes, if you look hard enough, you will always find a few places that any extra line space or two has crept in. These usually get filtered out with time. None of them are causing problems.
> 
> Screenshot at 2023-12-27 13-10-19
> 
> Any serious coder will be using a large 4K screen of course and a modern multipanel IDE with filter extensions and mini-map navigation ... Maybe this is the move you need to make?
> 
> Screenshot at 2023-12-27 13-31-55
> 
> All the best for 2024 and for success with qrun.

I have to disagree with you here. Of course, the idea of removing all whitespaces is ridiculous and would degrade readability significantly. However, I've seen the code throughout this repository and find that it's even more difficult to read because of the vast number of whitespaces. I personally believe it's the best idea to only separate blocks of code that serve different functions with whitespaces, or the 'return' statements, especially in 'languages' like bash where you just print something into the console instead. Here, there's countless instances of random printf statements separated by whitespaces. This doesn't improve readability in the slightest. In addition, you're pointing to functions from different files you've sourced (never clearly marking where each comes from), and have other strange decisions like 300+ lines of if-else statements to check the value of 1 variable, which is far more difficult to read than switch cases (not to mention quite a bit slower, at least in the languages I'm more used to).

I don't see what's so readable about the code here and why it has to be preserved this way. In fact, a month or so ago I decided to try to create a PKGBUILD (Arch Linux build script) for this tool, but gave it up because of all of the trouble the whitespaces and variable declaration all over the place caused. Not to mention, other things like leaving a .desktop file in a random part of the script rather than somewhere else in the repository. I can't imagine how difficult it would be to maintain this codebase, even if you're the person who wrote it. Everything is needlessly complicated and spaced apart. At least half of your main script is just whitespace. I'd like to hear why you do this, or if you have some configuration in your text editor which improves the readability of code like this.

And although this doesn't matter for a bash script, you should learn more about licenses, and make sure to in the future suitably license your code. Vague wording like 'small code snippets may be used permissively' doesn't have a clear enough meaning and would have a reasonable likelihood of not holding up in a court if a proprietary software developer was discovered to have used dozens or hundreds of lines of your code. Not to mention, leaving 'or similar' in the licenses they can choose to use your code under essentially leaves your work up in the public domain. You can use either copyleft or permissive licenses, you should only consider dual licensing between the same type of license (i.e. how some projects are dual licensed under Apache-2.0 and MIT, both permissive licenses). The GPLv3 also requires that anyone using your code must show the original copyright, as well as instructions on how to obtain a copy of your software. Thus, the "you should show clear attributions" part is redundant, and once again a line like that with wording like 'should' would be of no use at actually protecting your code if you had chosen a license which doesn't have the stipulation.

**Comment by TuxVinyards** [comment]
"I have to disagree with you here. Of course ...."   :rofl:

**Pull request closed without merging**
